version: "3"
services:
  seq:
    image: datalust/seq
    ports:
      - '8080:80'
      - '5341:5341'
    volumes:
      - path/to/local/storage:/data
    enironment:
      - ACCEPT_EULA=Y
    networks:
      - gameapp_net
  backend:
    build: ./backend
    ports:
      - '5000:80'
    environment:
      - Rawg__Apikey=[YOUR_RAWG_API_KEY]
    networks:
      - gameapp_net
  frontend:
    build: ./frontend
    ports:
      - '80:80'

networks:
  gameapp_net:
    driver: bridge
    ipam:
      driver: default
